=== trishiamarie/training2020/BernaldoEx20/config/flightlist.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- declaring all of the elements -->
<!ELEMENT flightlist (flight+)>
<!ELEMENT flight (passengers+)>
<!ELEMENT passengers (passenger+)>
<!ELEMENT passenger EMPTY>

<!-- declaring added attributes in element: flight -->
<!ATTLIST flight number (1 | 2 | 3) #REQUIRED>
<!ATTLIST flight origin (BOS | SFO | NYC) #REQUIRED>
<!ATTLIST flight dest (SJU | JFK | MRY) #REQUIRED>

<!-- declaring added attributes in element: passengers -->
<!ATTLIST passengers date (12-4-2012 | 12-5-2012 | 12-5-2012 | 12-6-2012) #REQUIRED>

<!-- declaring added attributes in element: passenger -->
<!ATTLIST passenger name CDATA #REQUIRED>
<!ATTLIST passenger seat CDATA #REQUIRED>

=== trishiamarie/training2020/BernaldoEx20/config/flightlist.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- FOR DTD Validation: -->
<!-- <!DOCTYPE flightlist SYSTEM "flightlist.dtd"> -->

<!-- FOR XSD Validation: -->
<flightlist xmlns="http://www.77Global.org/flightlist" 
		   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		   xsi:schemaLocation="http://www.77Global.org/flightlist flightlist.xsd">
		   
	<flight number="1" origin="BOS" dest="SJU">
	
		<passengers date="2012-12-04">
			<passenger name ="Laura" seat="1A"/>
			<passenger name ="Anna" seat="1B"/>
		</passengers>
		
		<passengers date="2012-12-05">
			<passenger name ="Tatiana" seat="1C"/>
			<passenger name ="Candy" seat="1D"/>
		</passengers>
	
	</flight>
	
	<flight number="2" origin="SFO" dest="JFK">
	
		<passengers date="2012-12-04">
			<passenger name ="Charlie" seat="1A"/>
			<passenger name ="Ivan" seat="1B"/>
		</passengers>
		
		<passengers date="2012-12-05">
			<passenger name ="Dan" seat="1C"/>
			<passenger name ="Li" seat="1D"/>
		</passengers>
	
	</flight>
	
	<flight number="3" origin="NYC" dest="MRY">
	
		<passengers date="2012-12-05">
			<passenger name ="Eva" seat="2A"/>
			<passenger name ="Joshua" seat="2B"/>
		</passengers>
		
		<passengers date="2012-12-06">
			<passenger name ="Crizzy" seat="2C"/>
			<passenger name ="Lu" seat="2D"/>
		</passengers>
	
	</flight>
	
</flightlist>
